# Generated by Django 2.2 on 2022-08-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_eng',
            field=models.CharField(default='', max_length=60),
        ),
    ]
