# Generated by Django 2.2 on 2022-08-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0003_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='opening',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
