# Generated by Django 2.2 on 2022-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0004_auto_20220809_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opening',
            name='url',
            field=models.URLField(),
        ),
    ]
