# Generated by Django 3.2.6 on 2022-08-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0007_auto_20220812_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vtmodel',
            name='word5_code',
        ),
        migrations.RemoveField(
            model_name='vtmodel',
            name='word5_name',
        ),
        migrations.RemoveField(
            model_name='vtmodel',
            name='word5_ngram',
        ),
        migrations.RemoveField(
            model_name='vtmodel',
            name='word5_sim',
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word1_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word1_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word2_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word2_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word3_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word3_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word4_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='vtmodel',
            name='word4_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
    ]
