# Generated by Django 3.2.6 on 2022-08-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0008_auto_20220812_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtmodel',
            name='word5_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='vtmodel',
            name='word5_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='vtmodel',
            name='word5_ngram',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='vtmodel',
            name='word5_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
    ]
