# Generated by Django 3.2.6 on 2022-08-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0009_auto_20220812_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinamodel',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
