# Generated by Django 3.2.6 on 2022-08-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0010_alter_chinamodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinamodel',
            name='word1_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word1_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word1_ngram',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word1_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word2_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word2_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word2_ngram',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word2_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word3_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word3_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word3_ngram',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word3_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word4_code',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word4_name',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word4_ngram',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AddField(
            model_name='chinamodel',
            name='word4_sim',
            field=models.CharField(default='NaN', max_length=100),
        ),
        migrations.AlterField(
            model_name='chinamodel',
            name='date',
            field=models.DateField(),
        ),
    ]
