# Generated by Django 3.2.6 on 2022-08-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0011_auto_20220817_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('word1_ngram', models.CharField(default='NaN', max_length=100)),
                ('word1_code', models.CharField(default='NaN', max_length=100)),
                ('word1_name', models.CharField(default='NaN', max_length=100)),
                ('word1_sim', models.CharField(default='NaN', max_length=100)),
                ('word2_ngram', models.CharField(default='NaN', max_length=100)),
                ('word2_code', models.CharField(default='NaN', max_length=100)),
                ('word2_name', models.CharField(default='NaN', max_length=100)),
                ('word2_sim', models.CharField(default='NaN', max_length=100)),
                ('word3_ngram', models.CharField(default='NaN', max_length=100)),
                ('word3_code', models.CharField(default='NaN', max_length=100)),
                ('word3_name', models.CharField(default='NaN', max_length=100)),
                ('word3_sim', models.CharField(default='NaN', max_length=100)),
                ('word4_ngram', models.CharField(default='NaN', max_length=100)),
                ('word4_code', models.CharField(default='NaN', max_length=100)),
                ('word4_name', models.CharField(default='NaN', max_length=100)),
                ('word4_sim', models.CharField(default='NaN', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AuModel',
        ),
        migrations.DeleteModel(
            name='ChinaModel',
        ),
        migrations.DeleteModel(
            name='JapanModel',
        ),
        migrations.DeleteModel(
            name='USAModel',
        ),
        migrations.DeleteModel(
            name='VtModel',
        ),
    ]
