# Generated by Django 3.2.6 on 2022-08-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0012_auto_20220817_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='img_path',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='txt',
            field=models.CharField(default='고시정보 출처 설명', max_length=200),
        ),
    ]
