# Generated by Django 3.2.6 on 2022-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0013_auto_20220818_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
