# Generated by Django 3.2.6 on 2022-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0015_headoffice_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='txt',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
