# Generated by Django 3.2.6 on 2022-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0016_headoffice_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='txt_eng',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
