# Generated by Django 3.2.6 on 2022-08-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0017_headoffice_txt_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hscode', models.CharField(max_length=10)),
                ('hscode_name', models.CharField(max_length=50)),
                ('KSIC10', models.CharField(max_length=10)),
                ('KSIC10_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='headoffice',
            name='country_eng',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='headoffice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
