# Generated by Django 3.2.6 on 2022-08-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0018_auto_20220819_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='headoffice',
            name='export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='headoffice',
            name='korea',
            field=models.BooleanField(default=False),
        ),
    ]
