# Generated by Django 3.2.6 on 2022-08-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0019_auto_20220821_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_china', models.CharField(max_length=200)),
                ('last_usa', models.CharField(max_length=200)),
                ('last_japan', models.CharField(max_length=200)),
                ('last_vietnam', models.CharField(max_length=200)),
                ('last_australia', models.CharField(max_length=200)),
            ],
        ),
    ]
