# Generated by Django 3.2.6 on 2022-08-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekho', '0020_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='industry',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
